apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-noauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-noauth
  template:
    metadata:
      labels:
        app: nginx-noauth
    spec:
      containers:
      - name: nginx
        image: <REPLACE_WITH_REG_NAME>/nginx-noauth:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-noauth-service
spec:
  selector:
    app: nginx-noauth
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80